### ISSUE TITLE
the mod is not working :(

### ISSUE THREAD

**Issue by ThecheeseDX** [infernalstudios/Nekos-Enchanted-Books#21]
i was trying to do a modpack myself to play with my friends but when i put the mod it doesn't seems to do anything, i tried using it only with optifine and it is still doesn't work, please help i love this mod (sorry bad english)

**Comment by Dariensg** [comment]
Could you provide more information, such as version (both MC and Forge version)?

**Comment by PabloCast525** [comment]
I have the same problem, but i didn't use optifine, i used Rubidium and Oculus, but also try with Optifine and it didn't work either, my minecraft version is 1.18.2 and my forge version is 40.1.68, sorry for my grammar, i don't speak english

**Comment by ThecheeseDX** [comment]
> Could you provide more information, such as version (both MC and Forge version)?

i'm playing the 1.16.5 version of MC and the 36.2.35 version of forge
