### ISSUE TITLE
Compat for Copper Overhaul

### ISSUE THREAD

**Issue by AgnyaAlm** [infernalstudios/Nekos-Enchanted-Books#23]
Could you guys add compatibility with Copper Overhaul's enchanted books? 
Currently it uses a texture pack that needs Optifine's CIT to work.

I'm the owner of the mod, so if you want feel free to include the [texture pack](https://www.curseforge.com/minecraft/texture-packs/copper-overhaul-cit)'s book textures. :)

Mod CF link: https://www.curseforge.com/minecraft/mc-mods/copper-overhaul

**Comment by nekomaster1000** [comment]
Send me the textures over Discord and I'll do that! :D @Nekomaster#8663

**Comment by nekomaster** [comment]
> 

You pinged the wrong nekomaster on here buds :D

**Comment by nekomaster1000** [comment]
OH CRAP! It's the very first Nekomaster! Sorry for the ping! :"D

**Comment by nekomaster** [comment]
> 

No worries buds.
Hopefully you guys get your stuff done.
Kinda funny thought that I'd get pinged on a mod I probably will end up using at some point.

**Comment by nekomaster1000** [comment]
Done! https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books/files/4018073
