### ISSUE TITLE
Compat issue with Ma enchants

### ISSUE THREAD

**Issue by qwertyxcvb** [infernalstudios/Nekos-Enchanted-Books#24]
It doesnt show texture for Ma enchants i even put mod resources on top and it still doesnt load does it have a problem with the version or optifine?

**Comment by nekomaster1000** [comment]
This is because Ma Enchants changed it's modID between versions, it's a known issue and will be fixed in the next release.

**Comment by Dariensg** [comment]
Duplicate of #22
