### ISSUE TITLE
Missing Swift Sneak Texture

### ISSUE THREAD

**Issue by SM-I-LE** [infernalstudios/Nekos-Enchanted-Books#25]
Just letting you know that there is not texture for the swift sneak enchantment. :(

![image](https://user-images.githubusercontent.com/103612500/177372334-629ae0f2-dc58-467b-b1c5-278679a71b7f.png)

**Comment by Yoyoyokk** [comment]
hey guy，Version 1.19 (41.0.45) textures are not shown，what's problem?

**Comment by Dariensg** [comment]
Don’t comment on another issue with a different problem. If you have an issue, open your own issue report.

**Comment by nekomaster1000** [comment]
Fixed! https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books/files/4018073
