### ISSUE TITLE
Aileron compat

### ISSUE THREAD

**Issue by SwanX1** [infernalstudios/Nekos-Enchanted-Books#27]
Request for compat submitted by Hypremancy#3137 (id: 988435326865383464) on Discord.

Aileron CurseForge page: https://www.curseforge.com/minecraft/mc-mods/aileron, there is no source code.

Relevant info:
 - Smokestack Enchantment (`aileron:smokestack`)
   Allows the player to store boosts while crouching on campfires, consuming them with the jump key while flying for a burst of speed.
 - Cloudskipper Enchantment (`aileron:cloudskipper`)
   Horizontal drag is reduced depending on the player's altitude, allowing them to glide for much longer and at much higher speeds while above the cloud layer.

**Comment by nekomaster1000** [comment]
Done! https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books/files/4018073
