### ISSUE TITLE
Majrusz's Enchantments has added/removed enchantments

### ISSUE THREAD

**Issue by SwanX1** [infernalstudios/Nekos-Enchanted-Books#28]
The title is pretty self-explanatory. Wonderful Enchantments, as of its [1.7.0 release](https://github.com/Majrusz/MajruszsEnchantmentsMod/releases/tag/1.7.0
), has been renamed to Majrusz's Enchantments, the mod id now being `majruszsenchantments`.

There have been major changes to the mod too, including added and removed enchantments. A lot of enchantments have been reworked, so it would be wise to review existing textures to see if they fit with the new reworked functionality for these enchantments.

More information: https://github.com/Majrusz/MajruszsEnchantmentsMod/releases/tag/1.7.0

Added Enchantments:
 - `majruszsenchantments:breaking_curse`
 - `majruszsenchantments:death_wish`
 - `majruszsenchantments:fuse_cutter`
 - `majruszsenchantments:gold_fuelled`
 - `majruszsenchantments:guardian_angel`
 - `majruszsenchantments:horse_swiftness`
 - `majruszsenchantments:misanthropy`
 - `majruszsenchantments:sixth_sense`

Removed Enchantments:
 - `wonderfulenchantments:gotta_mine_fast`
 - `wonderfulenchantments:human_slayer`
 - `wonderfulenchantments:leeching`
 - `wonderfulenchantments:phoenix_dive`
 - `wonderfulenchantments:pufferfish_vengeance`
 - `wonderfulenchantments:slowness_curse`
 - `wonderfulenchantments:swiftness`
 
Props to [MisterBlueTopaz](https://www.curseforge.com/members/misterbluetopaz) on CurseForge for letting us know about this issue: 
[![MisterBlueTopaz: This mod no longer seems to work with Wonderful Enchantments after it was renamed to 'Majrusz's Enchantments'](https://user-images.githubusercontent.com/36593309/184237698-6f2df180-ea38-4246-ad3e-cb0ce0bef361.png)](https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books?comment=252)

**Comment by nekomaster1000** [comment]
[Fixed in 1.7.1!](https://github.com/infernalstudios/Nekos-Enchanted-Books/commit/ce0c90bbbec2f2aa16441ffc42791dd1a327136f)

**Comment by SwanX1** [comment]
not fixed

**Comment by nekomaster1000** [comment]
Oh whoops I only read half of this again last night as I was going to bed HAHA, I’ll get on these new ones for 1.8

**Comment by nekomaster1000** [comment]
Done for real this time LOL https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books/files/4018073
