### ISSUE TITLE
Enchanted Books compat for more mods

### ISSUE THREAD

**Issue by Kutzeee** [infernalstudios/Nekos-Enchanted-Books#3]
Hey, I really like this mod and makes enchanted books feel more special and aesthetically pleasing. There are a few mods that I would suggest adding textures for, these being:

[Alex's Mobs](url)
[Allurement](url)
[Astral Sorcery](url)
[Big Brain](url)
[CoFH Core](url)
[Fins and Tails](url)
[Forbidden and Arcanus](url)
[Guns Without Roses](url)
[Spartan Shields](url)

**Comment by VaIerka** [comment]
+1
Cursed

**Comment by Blugori** [comment]
I am sorry to add more mods to the list ! It would be so great if you could had textures for some other mods :
Basalt Walker
Shulker enchantments
Soulbound

If you need/want help, I can somehow manage to create the textures for the mods I'm asking for

**Comment by Nebula240** [comment]
> Hey, I really like this mod and makes enchanted books feel more special and aesthetically pleasing. There are a few mods that I would suggest adding textures for, these being:
> 
> [Alex's Mobs](url)
> [Allurement](url)
> [Astral Sorcery](url)
> [Big Brain](url)
> [CoFH Core](url)
> [Fins and Tails](url)
> [Forbidden and Arcanus](url)
> [Guns Without Roses](url)
> [Spartan Shields](url)

Allurement and alex mobs have just been finished!! Will be added in the next update :)

**Comment by Lykrast** [comment]
Can't make proper textures for PRs but as a very small help here's all the enchantment keys for all those mods, for a lil convenience. Disclaimer I haven't checked in game.

* Astral Sorcery
```
  "enchantment.astralsorcery.night_vision": XX.01,
  "enchantment.astralsorcery.scorching_heat": XX.02,
```
* Big Brain
```
  "enchantment.bigbrain.turning": XX.01,
  "enchantment.bigbrain.bang": XX.02,
```
* CoFH Core *(disabled is called "Shimmer" and seems to be used for disabled CoFH mods enchantments, not sure if this mod catches it or not)*
```
  "enchantment.cofh_core.disabled": XX.01,
  "enchantment.cofh_core.holding": XX.02,
```
* Fins and Tails
```
  "enchantment.fins.fluked_edge": XX.01,
  "enchantment.fins.uppercutting": XX.02,
  "enchantment.fins.crabs_favor": XX.03,
```
* Forbidden and Arcanus
```
  "enchantment.forbidden_arcanus.permafrost": XX.01,
  "enchantment.forbidden_arcanus.indestructible": XX.02,
```
* Guns Without Roses *(hey it my mod!)*
```
  "enchantment.gunswithoutroses.impact": XX.01,
  "enchantment.gunswithoutroses.bullseye": XX.02,
  "enchantment.gunswithoutroses.sleight_of_hand": XX.03,
  "enchantment.gunswithoutroses.preserving": XX.04,
```
* Spartan Shields
```
  "enchantment.spartanshields.spikes": XX.01,
  "enchantment.spartanshields.firebrand": XX.02,
  "enchantment.spartanshields.payback": XX.03,
  "enchantment.spartanshields.deflect": XX.04,
```
* Cursed
```
  "enchantment.cursed.blindness": XX.01,
  "enchantment.cursed.curtail": XX.02,
  "enchantment.cursed.echo": XX.03,
  "enchantment.cursed.encumbrance": XX.04,
  "enchantment.cursed.fading": XX.05,
  "enchantment.cursed.fragility": XX.06,
  "enchantment.cursed.ignorance": XX.07,
  "enchantment.cursed.insomnia": XX.08,
  "enchantment.cursed.midas": XX.09,
  "enchantment.cursed.misfortune": XX.10,
  "enchantment.cursed.obedience": XX.11,
  "enchantment.cursed.radiance": XX.12,
  "enchantment.cursed.silence": XX.13,
  "enchantment.cursed.sinking": XX.14,
  "enchantment.cursed.ruin": XX.15,
  "enchantment.cursed.dullness": XX.16,
  "enchantment.cursed.delicacy": XX.17,
```
* Basalt Walker
```
  "enchantment.basalt_walker.basalt_walker": XX.01,
```
* Soulbound
```
  "enchantment.soulbound.soulbound": XX.01,
```
