### ISSUE TITLE
Compat request for the Block Swapper mod

### ISSUE THREAD

**Issue by Kuraion** [infernalstudios/Nekos-Enchanted-Books#32]
I would like to request compat for my new mod called Block Swapper. It adds hammer-shaped tools that enable the player to swap placed blocks with blocks from the off-hand while keeping the original properties and orientation. Additionally, it adds one new treasure-only enchantment that can be applied to diamond-tier block swappers.

Relevant info:
Curseforge page: https://www.curseforge.com/minecraft/mc-mods/block-swapper
Source code: https://github.com/Kuraion/Block_Swapper

Enchantment info:
Excavating, an enchantment which enables the block swappers to swap blocks with air if the off-hand is empty, essentially destroying blocks very quickly.

**Comment by SwanX1** [comment]
Enchantment ResourceLocation: `blockswapper:excavating`

**Comment by nekomaster1000** [comment]
Great mod, friend! I'll try and get to this soon enough :D

**Comment by nekomaster1000** [comment]
Done! https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books/files/4018073
