### ISSUE TITLE
Unable to load structures with /load or structure blocks

### ISSUE THREAD

**Issue by Bonniethebunny-hub** [infernalstudios/Nekos-Enchanted-Books#33]
Version: Latest (1.19.2)
Issue: Unable to load structures with /load or structure blocks, able to do so with vanilla structures
Mods installed: Infernal Expansion, no others
Forge version: forge-1.19.2-43.1.27

**Comment by SwanX1** [comment]
excuse me miss, the issue tracker you're looking for is [infernalstudios/Infernal-Expansion](https://github.com/infernalstudios/Infernal-Expansion/issues). this is the neko's enchanted books' issue tracker
