### ISSUE TITLE
1.19.2 Strange Startup Issue - Random Failure.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [infernalstudios/Nekos-Enchanted-Books#38]
![6FwFne5 1](https://user-images.githubusercontent.com/10351221/195084450-dfa046ea-5195-490b-bdae-1ce44ad2a0c8.png)

Forge: 43.1.34
Mod Version: NekosEnchantedBooks-1.19-1.8.0

I was working on it my partner distracted me (I have ADD)

[latest.log](https://github.com/infernalstudios/Nekos-Enchanted-Books/files/9754924/latest.log)

**Comment by SwanX1** [comment]
please provide a game log/crash report

**Comment by P3rf3ctXZer0** [comment]
https://github.com/infernalstudios/Nekos-Enchanted-Books/issues/38#issue-1404521257

**Comment by Maltshakes** [comment]
I also have this issue, I've attached the crash log 

[crash-2022-11-26_21.52.06-fml.txt](https://github.com/infernalstudios/Nekos-Enchanted-Books/files/10097001/crash-2022-11-26_21.52.06-fml.txt)

**Comment by Jonathing** [comment]
I've fixed this in #57. This is an extremely rare bug that won't always occur unless two mods, at just the right time, try to add client item properties.
