### ISSUE TITLE
[Request] Seperate Mod for Potions

### ISSUE THREAD

**Issue by Shibva** [infernalstudios/Nekos-Enchanted-Books#45]
What have you done here is brillant. this has to be the only mod that ive seen that is able to assign a texture from a Minecraft item based on its contents. this may not be realized; but this sort of thing is perfect for using resource packs and altering them to work wtih this mods assets wtihout the use of Optifine.

what im getting at here is that it would be nice if there was something like this that worked for potions and is also client based. It can be things like this that can give people that use mods like Rubidium the option to still enjoy some texture packs that would need to rely on optifine for it to work;

**Comment by SwanX1** [comment]
Thank you for the suggestion, however we most likely will not be working on this in the near future.
