### ISSUE TITLE
Servers Incompatible with mod

### ISSUE THREAD

**Issue by XxLionTheWolfxX** [infernalstudios/Nekos-Enchanted-Books#46]
Servers fail to load, including hosting to LAN when this mod is enabled. 

No other mods present.

[crash-2023-06-24_17.35.24-fml.txt](https://github.com/infernalstudios/Nekos-Enchanted-Books/files/11858346/crash-2023-06-24_17.35.24-fml.txt)

**Comment by Dariensg** [comment]
It's a client-side mod. It shouldn't be on the server.

**Comment by Linguardium** [comment]
then it should be developed correctly according to the forge dev documentation

https://docs.minecraftforge.net/en/latest/concepts/sides/#writing-one-sided-mods
