### ISSUE TITLE
[Feature Request/Feature Offer] Make this mod also available for 1.20.1 as a Resource Pack (I've managed to convert it automatically too)

### ISSUE THREAD

**Issue by TBlazeWarriorT** [infernalstudios/Nekos-Enchanted-Books#49]
The title is pretty self-explanatory

But also, I wanted this rn for myself so it would save me some effort from making a full Add-on for Xali's Enchanted Books, which is what I'm using

So I've written a node.js Replit that automatically converts this mods' format back into OptiFine/Cit Resewn format (currently takes a modified version of properties.json and generates a valid .properties file for each enchantment, including some nice folder structure for each mod)

As you can see I'm already using it privately for myself
So since converting it (including future compatibility that should keep working) took me just around an hour (and now re-generating it takes just 3 minutes), I decided to suggest this.
I wouldn't mind sharing my conversion code or output resource pack if needed, etc, everything is private rn because copyright but ey if it's the dev reading this just ask and it's here if you want it

_(Also I'll probably make my own textures for the enchantments that are missing, I can't find any resource pack, mod or mix of multiple of those that is complete enough to cover all enchanted books, and this is what got the closest. Maybe in a few years we will have AI generate textures for other mods' enchantments dynamically, but anyways, this is getting unrelated)_

I saw the 1.20 branch so I know it's probably going to be updated as a mod too eventually, but having it available as a resource pack given how popular this mod is (you'll be getting to 10M downloads soon!) is probably very worth it, also because CIT Resewn now exists

Screenshot showing me using this mod as an RP in 1.20.1
![image](https://github.com/infernalstudios/Nekos-Enchanted-Books/assets/25572454/539da2d0-5a9e-4f8f-81fb-495aa4f21ed5)

**Comment by SwanX1** [comment]
Hi! Unfortunately, the goal of this mod isn't for it to be dependent on OptiFine. This was created to fix the issue of not being able to give books custom textures without OF resource packs.

If you want specific mods to be supported, go ahead and suggest them for compatibility in a seperate issue.

**Comment by SwanX1** [comment]
Additionally, if you'd like to contribute with your own textures for mods, feel free to make a pull request (adding textures is documented in the README), and @nekomaster1000 will take a look to see if your textures are a good fit for the mod.

If you don't want to include your own textures in our mod, but use them regardless, feel free to try the approach in [my comment on issue #14](https://github.com/infernalstudios/Nekos-Enchanted-Books/issues/14#issuecomment-1097616829).

**Comment by TBlazeWarriorT** [comment]
> Hi! Unfortunately, the goal of this mod isn't for it to be dependent on OptiFine. This was created to fix the issue of not being able to give books custom textures without OF resource packs.
> 
> 
> 
> If you want specific mods to be supported, go ahead and suggest them for compatibility in a seperate issue.

I'm not using optifine on the screenshot, it's CIT resewn which is viable
Anyways, I ended up talking to Neko and the conclusion was kinda similar
Thanks anyways
